package entidades;

// Generated 01/09/2015 00:07:35 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AlertasId generated by hbm2java
 */
@Entity
@Table(name = "alertas", catalog = "rfid_maternidade")
public class Alertas implements java.io.Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = -2582465086287795597L;
	private int cdAlerta;
	private int cdTipoAlerta;
	private int cdMovimentacao;
	private String sn_verificado;
	private String cd_usuario;
	private Date dt_verificado;
	
	
	@Column(name = "sn_verificado", nullable = false)
	public String getSn_verificado() {
		return sn_verificado;
	}

	public void setSn_verificado(String sn_verificado) {
		this.sn_verificado = sn_verificado;
	}

	@Column(name = "cd_usuario", nullable = false)
	public String getCd_usuario() {
		return cd_usuario;
	}

	public void setCd_usuario(String cd_usuario) {
		this.cd_usuario = cd_usuario;
	}

	@Column(name = "dt_verificado", nullable = false)
	public Date getDt_verificado() {
		return dt_verificado;
	}

	public void setDt_verificado(Date dt_verificado) {
		this.dt_verificado = dt_verificado;
	}

	public Alertas() {
	}

	public Alertas(int cdAlerta, int tipoAlertaCdTipoAlerta,int cdMovimentacao) {
		this.cdAlerta = cdAlerta;
		this.cdTipoAlerta = tipoAlertaCdTipoAlerta;
		this.cdMovimentacao = cdMovimentacao;
	}
	
	public Alertas(int tipoAlertaCdTipoAlerta,int cdMovimentacao) {
		this.cdAlerta = cdAlerta;
		this.cdTipoAlerta = tipoAlertaCdTipoAlerta;
		this.cdMovimentacao = cdMovimentacao;
	}
	public Alertas(int tipoAlertaCdTipoAlerta,int cdMovimentacao,String sn) {
		this.cdAlerta = cdAlerta;
		this.cdTipoAlerta = tipoAlertaCdTipoAlerta;
		this.cdMovimentacao = cdMovimentacao;
		this.sn_verificado =sn;
	}
	@Column(name = "cd_alerta", nullable = false)
	public int getCdAlerta() {
		return this.cdAlerta;
	}

	public void setCdAlerta(int cdAlerta) {
		this.cdAlerta = cdAlerta;
	}

	

	@Column(name = "cd_tipo_alerta", nullable = false)
	public int getTipoAlerta() {
		return cdTipoAlerta;
	}

	public void setTipoAlerta(int tipoAlertaCdTipoAlerta) {
		this.cdTipoAlerta = tipoAlertaCdTipoAlerta;
	}


	@Id
	@Column(name = "cd_movimentacao")
	public int getCdMovimentacao() {
		return this.cdMovimentacao;
	}

	public void setCdMovimentacao(int cdMovimentacao) {
		this.cdMovimentacao = cdMovimentacao;

	}
}
