package entidades;

// Generated 17/10/2015 19:11:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Alertas generated by hbm2java
 */
@Entity
@Table(name = "alertas", catalog = "rfid_maternidade")
public class Alertas implements java.io.Serializable {

	private AlertasId id;
	private TipoAlerta tipoAlerta;
	private Integer cdMovimentacao;

	public Alertas() {
	}

	public Alertas(AlertasId id, TipoAlerta tipoAlerta) {
		this.id = id;
		this.tipoAlerta = tipoAlerta;
	}

	public Alertas(AlertasId id, TipoAlerta tipoAlerta, Integer cdMovimentacao) {
		this.id = id;
		this.tipoAlerta = tipoAlerta;
		this.cdMovimentacao = cdMovimentacao;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdAlerta", column = @Column(name = "cd_alerta", nullable = false)),
			@AttributeOverride(name = "tipoAlertaCdTipoAlerta", column = @Column(name = "tipo_alerta_cd_tipo_alerta", nullable = false)) })
	public AlertasId getId() {
		return this.id;
	}

	public void setId(AlertasId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo_alerta_cd_tipo_alerta", nullable = false, insertable = false, updatable = false)
	public TipoAlerta getTipoAlerta() {
		return this.tipoAlerta;
	}

	public void setTipoAlerta(TipoAlerta tipoAlerta) {
		this.tipoAlerta = tipoAlerta;
	}

	@Column(name = "cd_movimentacao")
	public Integer getCdMovimentacao() {
		return this.cdMovimentacao;
	}

	public void setCdMovimentacao(Integer cdMovimentacao) {
		this.cdMovimentacao = cdMovimentacao;
	}

}
