package entidades;

// Generated 17/10/2015 19:11:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AlertasId generated by hbm2java
 */
@Embeddable
public class AlertasId implements java.io.Serializable {

	private int cdAlerta;
	private int tipoAlertaCdTipoAlerta;

	public AlertasId() {
	}

	public AlertasId(int cdAlerta, int tipoAlertaCdTipoAlerta) {
		this.cdAlerta = cdAlerta;
		this.tipoAlertaCdTipoAlerta = tipoAlertaCdTipoAlerta;
	}

	@Column(name = "cd_alerta", nullable = false)
	public int getCdAlerta() {
		return this.cdAlerta;
	}

	public void setCdAlerta(int cdAlerta) {
		this.cdAlerta = cdAlerta;
	}

	@Column(name = "tipo_alerta_cd_tipo_alerta", nullable = false)
	public int getTipoAlertaCdTipoAlerta() {
		return this.tipoAlertaCdTipoAlerta;
	}

	public void setTipoAlertaCdTipoAlerta(int tipoAlertaCdTipoAlerta) {
		this.tipoAlertaCdTipoAlerta = tipoAlertaCdTipoAlerta;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AlertasId))
			return false;
		AlertasId castOther = (AlertasId) other;

		return (this.getCdAlerta() == castOther.getCdAlerta())
				&& (this.getTipoAlertaCdTipoAlerta() == castOther
						.getTipoAlertaCdTipoAlerta());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCdAlerta();
		result = 37 * result + this.getTipoAlertaCdTipoAlerta();
		return result;
	}

}
