package entidades;

// Generated 01/09/2015 00:07:35 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Setor generated by hbm2java
 */
@Entity
@Table(name = "alertas_gerados", catalog = "rfid_maternidade")
public class AlertasGerados implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8085741406418633894L;
	private int cd_alerta;
	private int cd_movimentacao;
	private int cd_tp_alerta;
	private Date dt_movimentacao;
	private int cd_antena;
	private String ds_antena;
	private int cd_atendimento;
	private String nm_paciente;
	private String ds_tipo_alerta;	
	
	
	
	public String getNm_paciente() {
		return nm_paciente;
	}

	public void setNm_paciente(String nm_paciente) {
		this.nm_paciente = nm_paciente;
	}

	@Id
	@Column(name = "cd_alerta")
	public int getCd_alerta() {
		return cd_alerta;
	}

	public void setCd_alerta(int cd_alerta) {
		this.cd_alerta = cd_alerta;
	}

	@Column(name = "cd_movimentacao")
	public int getCd_movimentacao() {
		return cd_movimentacao;
	}

	public void setCd_movimentacao(int cd_movimentacao) {
		this.cd_movimentacao = cd_movimentacao;
	}

	@Column(name = "cd_tp_alerta")
	public int getCd_tp_alerta() {
		return cd_tp_alerta;
	}

	public void setCd_tp_alerta(int cd_tp_alerta) {
		this.cd_tp_alerta = cd_tp_alerta;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_movimentacao")
	public Date getDt_movimentacao() {
		return dt_movimentacao;
	}

	public void setDt_movimentacao(Date dt_movimentacao) {
		this.dt_movimentacao = dt_movimentacao;
	}

	@Column(name = "cd_antena")
	public int getCd_antena() {
		return cd_antena;
	}

	public void setCd_antena(int cd_antena) {
		this.cd_antena = cd_antena;
	}

	@Column(name = "ds_antena")
	public String getDs_antena() {
		return ds_antena;
	}

	public void setDs_antena(String ds_antena) {
		this.ds_antena = ds_antena;
	}

	@Column(name = "cd_atendimento")
	public int getCd_atendimento() {
		return cd_atendimento;
	}

	public void setCd_atendimento(int cd_atendimento) {
		this.cd_atendimento = cd_atendimento;
	}


	@Column(name = "ds_tipo_alerta")
	public String getDs_tipo_alerta() {
		return ds_tipo_alerta;
	}

	public void setDs_tipo_alerta(String ds_tipo_alerta) {
		this.ds_tipo_alerta = ds_tipo_alerta;
	}



}
