package entidades;

// Generated 17/10/2015 19:11:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Antenas generated by hbm2java
 */
@Entity
@Table(name = "antenas", catalog = "rfid_maternidade")
public class Antenas implements java.io.Serializable {

	private AntenasId id;
	private Setor setor;
	private String dsAntena;

	public Antenas() {
	}

	public Antenas(AntenasId id, Setor setor, String dsAntena) {
		this.id = id;
		this.setor = setor;
		this.dsAntena = dsAntena;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdAntena", column = @Column(name = "cd_antena", nullable = false)),
			@AttributeOverride(name = "cdIp", column = @Column(name = "cd_ip", nullable = false, length = 18)) })
	public AntenasId getId() {
		return this.id;
	}

	public void setId(AntenasId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "setor_cd_setor", nullable = false)
	public Setor getSetor() {
		return this.setor;
	}

	public void setSetor(Setor setor) {
		this.setor = setor;
	}

	@Column(name = "ds_antena", nullable = false, length = 50)
	public String getDsAntena() {
		return this.dsAntena;
	}

	public void setDsAntena(String dsAntena) {
		this.dsAntena = dsAntena;
	}

}
