package entidades;

// Generated 01/09/2015 00:07:35 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Atendimento generated by hbm2java
 */
@Entity
@Table(name = "atendimento", catalog = "rfid_maternidade")
public class Atendimento implements java.io.Serializable {

	private int cdAtendimento;
	private int cdPaciente;
	private Date dtAtendimento;
	private Date dtAlta;
	private String cdUsuarioSaida;
	private String cdUsuarioEntrada;

	public Atendimento(){
		
	}
	
	public Atendimento(int paciente, String usuario) {
		this.cdPaciente = paciente;
		this.cdUsuarioEntrada = usuario;
	}

	public Atendimento(int cdAtendimento, int cdPaciente,
			String cdUsuarioSaida, String usuarioCdUsuario) {
		this.cdAtendimento = cdAtendimento;
		this.cdPaciente = cdPaciente;
		this.cdUsuarioSaida = cdUsuarioSaida;
	}
	
	public Atendimento( int cdPaciente,
			Date dtAtendimento,
			String cdUsuarioEntrada) {
		this.cdPaciente = cdPaciente;
		this.dtAtendimento = dtAtendimento;
		this.cdUsuarioEntrada = cdUsuarioEntrada;
	}

	

	@Id
	@Column(name = "cd_atendimento", unique = true, nullable = false)
	public int getCdAtendimento() {
		return this.cdAtendimento;
	}

	public void setCdAtendimento(int cdAtendimento) {
		this.cdAtendimento = cdAtendimento;
	}

	@Column(name = "cd_paciente", nullable = false)
	public int getCdPaciente() {
		return this.cdPaciente;
	}

	public void setCdPaciente(int cdPaciente) {
		this.cdPaciente = cdPaciente;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_atendimento", length = 10)
	public Date getDtAtendimento() {
		return this.dtAtendimento;
	}

	public void setDtAtendimento(Date dtAtendimento) {
		this.dtAtendimento = dtAtendimento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_alta", length = 10)
	public Date getDtAlta() {
		return this.dtAlta;
	}

	public void setDtAlta(Date dt_alta) {
		this.dtAlta = dt_alta;
	}

	@Column(name = "cd_usuario_saida", length = 20)
	public String getCdUsuarioSaida() {
		return this.cdUsuarioSaida;
	}

	public void setCdUsuarioSaida(String cdUsuarioSaida) {
		this.cdUsuarioSaida = cdUsuarioSaida;
	}

	@Column(name = "cd_usuario_entrada", length = 20)
	public String getCdUsuarioEntrada() {
		return this.cdUsuarioEntrada;
	}

	public void setCdUsuarioEntrada(String cdUsuarioEntrada) {
		this.cdUsuarioEntrada = cdUsuarioEntrada;
	}

	

}
