package entidades;

// Generated 01/09/2015 00:07:35 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Atendimento generated by hbm2java
 */
@Entity
@Table(name = "atendimento", catalog = "rfid_maternidade")
public class Atendimento implements java.io.Serializable {

	private int cdAtendimento;
	private Integer cdAutorizacaoSaida;
	private int cdPaciente;
	private Date dtAtendimento;
	private Date dtAutorizacaoSaida;
	private String cdUsuarioSaida;
	private String cdUsuarioEntrada;
	private String usuarioCdUsuario;

	public Atendimento() {
	}

	public Atendimento(int cdAtendimento, int cdPaciente,
			String cdUsuarioSaida, String usuarioCdUsuario) {
		this.cdAtendimento = cdAtendimento;
		this.cdPaciente = cdPaciente;
		this.cdUsuarioSaida = cdUsuarioSaida;
		this.usuarioCdUsuario = usuarioCdUsuario;
	}

	public Atendimento(int cdAtendimento, Integer cdAutorizacaoSaida,
			int cdPaciente, Date dtAtendimento, Date dtAutorizacaoSaida,
			String cdUsuarioSaida, String cdUsuarioEntrada,
			String usuarioCdUsuario) {
		this.cdAtendimento = cdAtendimento;
		this.cdAutorizacaoSaida = cdAutorizacaoSaida;
		this.cdPaciente = cdPaciente;
		this.dtAtendimento = dtAtendimento;
		this.dtAutorizacaoSaida = dtAutorizacaoSaida;
		this.cdUsuarioSaida = cdUsuarioSaida;
		this.cdUsuarioEntrada = cdUsuarioEntrada;
		this.usuarioCdUsuario = usuarioCdUsuario;
	}

	@Id
	@Column(name = "cd_atendimento", unique = true, nullable = false)
	public int getCdAtendimento() {
		return this.cdAtendimento;
	}

	public void setCdAtendimento(int cdAtendimento) {
		this.cdAtendimento = cdAtendimento;
	}

	@Column(name = "cd_autorizacao_saida")
	public Integer getCdAutorizacaoSaida() {
		return this.cdAutorizacaoSaida;
	}

	public void setCdAutorizacaoSaida(Integer cdAutorizacaoSaida) {
		this.cdAutorizacaoSaida = cdAutorizacaoSaida;
	}

	@Column(name = "cd_paciente", nullable = false)
	public int getCdPaciente() {
		return this.cdPaciente;
	}

	public void setCdPaciente(int cdPaciente) {
		this.cdPaciente = cdPaciente;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_atendimento", length = 10)
	public Date getDtAtendimento() {
		return this.dtAtendimento;
	}

	public void setDtAtendimento(Date dtAtendimento) {
		this.dtAtendimento = dtAtendimento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_autorizacao_saida", length = 10)
	public Date getDtAutorizacaoSaida() {
		return this.dtAutorizacaoSaida;
	}

	public void setDtAutorizacaoSaida(Date dtAutorizacaoSaida) {
		this.dtAutorizacaoSaida = dtAutorizacaoSaida;
	}

	@Column(name = "cd_usuario_saida", nullable = false, length = 20)
	public String getCdUsuarioSaida() {
		return this.cdUsuarioSaida;
	}

	public void setCdUsuarioSaida(String cdUsuarioSaida) {
		this.cdUsuarioSaida = cdUsuarioSaida;
	}

	@Column(name = "cd_usuario_entrada", length = 20)
	public String getCdUsuarioEntrada() {
		return this.cdUsuarioEntrada;
	}

	public void setCdUsuarioEntrada(String cdUsuarioEntrada) {
		this.cdUsuarioEntrada = cdUsuarioEntrada;
	}

	@Column(name = "usuario_cd_usuario", nullable = false, length = 20)
	public String getUsuarioCdUsuario() {
		return this.usuarioCdUsuario;
	}

	public void setUsuarioCdUsuario(String usuarioCdUsuario) {
		this.usuarioCdUsuario = usuarioCdUsuario;
	}

}
