package entidades;

// Generated 17/10/2015 19:11:37 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Atendimento generated by hbm2java
 */
@Entity
@Table(name = "atendimento", catalog = "rfid_maternidade")
public class Atendimento implements java.io.Serializable {

	private int cdAtendimento;
	private Paciente paciente;
	private Usuario usuario;
	private Date dtAtendimento;
	private String cdUsuarioSaida;
	private Date dtSaida;
	private Set observacoeses = new HashSet(0);
	private Set tagsAtendimentos = new HashSet(0);
	private Set autorizacaoSaidas = new HashSet(0);
	private Set setorHasAtendimentos = new HashSet(0);

	public Atendimento() {
	}

	public Atendimento(int cdAtendimento, Paciente paciente,
			String cdUsuarioSaida) {
		this.cdAtendimento = cdAtendimento;
		this.paciente = paciente;
		this.cdUsuarioSaida = cdUsuarioSaida;
	}

	public Atendimento(int cdAtendimento, Paciente paciente, Usuario usuario,
			Date dtAtendimento, String cdUsuarioSaida, Date dtSaida,
			Set observacoeses, Set tagsAtendimentos, Set autorizacaoSaidas,
			Set setorHasAtendimentos) {
		this.cdAtendimento = cdAtendimento;
		this.paciente = paciente;
		this.usuario = usuario;
		this.dtAtendimento = dtAtendimento;
		this.cdUsuarioSaida = cdUsuarioSaida;
		this.dtSaida = dtSaida;
		this.observacoeses = observacoeses;
		this.tagsAtendimentos = tagsAtendimentos;
		this.autorizacaoSaidas = autorizacaoSaidas;
		this.setorHasAtendimentos = setorHasAtendimentos;
	}

	@Id
	@Column(name = "cd_atendimento", unique = true, nullable = false)
	public int getCdAtendimento() {
		return this.cdAtendimento;
	}

	public void setCdAtendimento(int cdAtendimento) {
		this.cdAtendimento = cdAtendimento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cd_paciente", nullable = false)
	public Paciente getPaciente() {
		return this.paciente;
	}

	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cd_usuario_entrada")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_atendimento", length = 10)
	public Date getDtAtendimento() {
		return this.dtAtendimento;
	}

	public void setDtAtendimento(Date dtAtendimento) {
		this.dtAtendimento = dtAtendimento;
	}

	@Column(name = "cd_usuario_saida", nullable = false, length = 20)
	public String getCdUsuarioSaida() {
		return this.cdUsuarioSaida;
	}

	public void setCdUsuarioSaida(String cdUsuarioSaida) {
		this.cdUsuarioSaida = cdUsuarioSaida;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_saida", length = 19)
	public Date getDtSaida() {
		return this.dtSaida;
	}

	public void setDtSaida(Date dtSaida) {
		this.dtSaida = dtSaida;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "atendimento")
	public Set getObservacoeses() {
		return this.observacoeses;
	}

	public void setObservacoeses(Set observacoeses) {
		this.observacoeses = observacoeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "atendimento")
	public Set getTagsAtendimentos() {
		return this.tagsAtendimentos;
	}

	public void setTagsAtendimentos(Set tagsAtendimentos) {
		this.tagsAtendimentos = tagsAtendimentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "atendimento")
	public Set getAutorizacaoSaidas() {
		return this.autorizacaoSaidas;
	}

	public void setAutorizacaoSaidas(Set autorizacaoSaidas) {
		this.autorizacaoSaidas = autorizacaoSaidas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "atendimento")
	public Set getSetorHasAtendimentos() {
		return this.setorHasAtendimentos;
	}

	public void setSetorHasAtendimentos(Set setorHasAtendimentos) {
		this.setorHasAtendimentos = setorHasAtendimentos;
	}

}
