package entidades;

// Generated 01/09/2015 00:07:35 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Modulo generated by hbm2java
 */
@Entity
@Table(name = "modulo", catalog = "rfid_maternidade")
public class Modulo implements java.io.Serializable {

	private int cdModulo;
	private String dsModulo;
	private String detalhe;

	public Modulo() {
	}

	public Modulo(int cdModulo) {
		this.cdModulo = cdModulo;
	}

	public Modulo(int cdModulo, String dsModulo, String detalhe) {
		this.cdModulo = cdModulo;
		this.dsModulo = dsModulo;
		this.detalhe = detalhe;
	}

	@Id
	@Column(name = "cd_modulo", unique = true, nullable = false)
	public int getCdModulo() {
		return this.cdModulo;
	}

	public void setCdModulo(int cdModulo) {
		this.cdModulo = cdModulo;
	}

	@Column(name = "ds_modulo", length = 50)
	public String getDsModulo() {
		return this.dsModulo;
	}

	public void setDsModulo(String dsModulo) {
		this.dsModulo = dsModulo;
	}

	@Column(name = "detalhe", length = 100)
	public String getDetalhe() {
		return this.detalhe;
	}

	public void setDetalhe(String detalhe) {
		this.detalhe = detalhe;
	}

}
