package entidades;

// Generated 17/10/2015 19:11:37 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Modulo generated by hbm2java
 */
@Entity
@Table(name = "modulo", catalog = "rfid_maternidade")
public class Modulo implements java.io.Serializable {

	private int cdModulo;
	private String dsModulo;
	private String detalhe;
	private Set usuarioHasModulos = new HashSet(0);

	public Modulo() {
	}

	public Modulo(int cdModulo) {
		this.cdModulo = cdModulo;
	}

	public Modulo(int cdModulo, String dsModulo, String detalhe,
			Set usuarioHasModulos) {
		this.cdModulo = cdModulo;
		this.dsModulo = dsModulo;
		this.detalhe = detalhe;
		this.usuarioHasModulos = usuarioHasModulos;
	}

	@Id
	@Column(name = "cd_modulo", unique = true, nullable = false)
	public int getCdModulo() {
		return this.cdModulo;
	}

	public void setCdModulo(int cdModulo) {
		this.cdModulo = cdModulo;
	}

	@Column(name = "ds_modulo", length = 50)
	public String getDsModulo() {
		return this.dsModulo;
	}

	public void setDsModulo(String dsModulo) {
		this.dsModulo = dsModulo;
	}

	@Column(name = "detalhe", length = 100)
	public String getDetalhe() {
		return this.detalhe;
	}

	public void setDetalhe(String detalhe) {
		this.detalhe = detalhe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modulo")
	public Set getUsuarioHasModulos() {
		return this.usuarioHasModulos;
	}

	public void setUsuarioHasModulos(Set usuarioHasModulos) {
		this.usuarioHasModulos = usuarioHasModulos;
	}

}
