package entidades;

// Generated 01/09/2015 00:07:35 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MovimentacaoAtendimentos generated by hbm2java
 */
@Entity
@Table(name = "movimentacao_atendimentos", catalog = "rfid_maternidade")
public class MovimentacaoAtendimentos implements java.io.Serializable {

	private MovimentacaoAtendimentosId id;
	private Date date;

	public MovimentacaoAtendimentos() {
	}

	public MovimentacaoAtendimentos(MovimentacaoAtendimentosId id) {
		this.id = id;
	}

	public MovimentacaoAtendimentos(MovimentacaoAtendimentosId id, Date date) {
		this.id = id;
		this.date = date;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdMovimentacao", column = @Column(name = "cd_movimentacao", nullable = false)),
			@AttributeOverride(name = "antenasCdAntena", column = @Column(name = "antenas_cd_antena", nullable = false)),
			@AttributeOverride(name = "tagsCdTag", column = @Column(name = "tags_cd_tag", nullable = false)) })
	public MovimentacaoAtendimentosId getId() {
		return this.id;
	}

	public void setId(MovimentacaoAtendimentosId id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
