package entidades;

// Generated 17/10/2015 19:11:37 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MovimentacaoPaciente generated by hbm2java
 */
@Entity
@Table(name = "movimentacao_paciente", catalog = "rfid_maternidade")
public class MovimentacaoPaciente implements java.io.Serializable {

	private Integer cdMovimentacao;
	private Date dtMovimentacao;
	private String cdIp;
	private String cdTag;

	public MovimentacaoPaciente() {
	}

	public MovimentacaoPaciente(Date dtMovimentacao, String cdIp, String cdTag) {
		this.dtMovimentacao = dtMovimentacao;
		this.cdIp = cdIp;
		this.cdTag = cdTag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cd_movimentacao", unique = true, nullable = false)
	public Integer getCdMovimentacao() {
		return this.cdMovimentacao;
	}

	public void setCdMovimentacao(Integer cdMovimentacao) {
		this.cdMovimentacao = cdMovimentacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_movimentacao", nullable = false, length = 19)
	public Date getDtMovimentacao() {
		return this.dtMovimentacao;
	}

	public void setDtMovimentacao(Date dtMovimentacao) {
		this.dtMovimentacao = dtMovimentacao;
	}

	@Column(name = "cd_ip", nullable = false, length = 18)
	public String getCdIp() {
		return this.cdIp;
	}

	public void setCdIp(String cdIp) {
		this.cdIp = cdIp;
	}

	@Column(name = "cd_tag", nullable = false, length = 100)
	public String getCdTag() {
		return this.cdTag;
	}

	public void setCdTag(String cdTag) {
		this.cdTag = cdTag;
	}

}
