package entidades;

// Generated 01/09/2015 00:07:35 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Observacoes generated by hbm2java
 */
@Entity
@Table(name = "observacoes", catalog = "rfid_maternidade")
public class Observacoes implements java.io.Serializable {

	private ObservacoesId id;
	private String dsObservacao;

	public Observacoes() {
	}

	public Observacoes(ObservacoesId id) {
		this.id = id;
	}

	public Observacoes(ObservacoesId id, String dsObservacao) {
		this.id = id;
		this.dsObservacao = dsObservacao;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdObservacao", column = @Column(name = "cd_observacao", nullable = false)),
			@AttributeOverride(name = "cdAtendimento", column = @Column(name = "cd_atendimento", nullable = false)),
			@AttributeOverride(name = "cdAutorizacaoSaida", column = @Column(name = "cd_autorizacao_saida", nullable = false)),
			@AttributeOverride(name = "cdPaciente", column = @Column(name = "cd_paciente", nullable = false)) })
	public ObservacoesId getId() {
		return this.id;
	}

	public void setId(ObservacoesId id) {
		this.id = id;
	}

	@Column(name = "ds_observacao", length = 1000)
	public String getDsObservacao() {
		return this.dsObservacao;
	}

	public void setDsObservacao(String dsObservacao) {
		this.dsObservacao = dsObservacao;
	}

}
