package entidades;

// Generated 17/10/2015 19:11:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Observacoes generated by hbm2java
 */
@Entity
@Table(name = "observacoes", catalog = "rfid_maternidade")
public class Observacoes implements java.io.Serializable {

	private int cdObservacao;
	private Atendimento atendimento;
	private String dsObservacao;

	public Observacoes() {
	}

	public Observacoes(int cdObservacao, Atendimento atendimento) {
		this.cdObservacao = cdObservacao;
		this.atendimento = atendimento;
	}

	public Observacoes(int cdObservacao, Atendimento atendimento,
			String dsObservacao) {
		this.cdObservacao = cdObservacao;
		this.atendimento = atendimento;
		this.dsObservacao = dsObservacao;
	}

	@Id
	@Column(name = "cd_observacao", unique = true, nullable = false)
	public int getCdObservacao() {
		return this.cdObservacao;
	}

	public void setCdObservacao(int cdObservacao) {
		this.cdObservacao = cdObservacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cd_atendimento", nullable = false)
	public Atendimento getAtendimento() {
		return this.atendimento;
	}

	public void setAtendimento(Atendimento atendimento) {
		this.atendimento = atendimento;
	}

	@Column(name = "ds_observacao", length = 1000)
	public String getDsObservacao() {
		return this.dsObservacao;
	}

	public void setDsObservacao(String dsObservacao) {
		this.dsObservacao = dsObservacao;
	}

}
