package entidades;

// Generated 01/09/2015 00:07:35 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ObservacoesId generated by hbm2java
 */
@Embeddable
public class ObservacoesId implements java.io.Serializable {

	private int cdObservacao;
	private int cdAtendimento;
	private int cdAutorizacaoSaida;
	private int cdPaciente;

	public ObservacoesId() {
	}

	public ObservacoesId(int cdObservacao, int cdAtendimento,
			int cdAutorizacaoSaida, int cdPaciente) {
		this.cdObservacao = cdObservacao;
		this.cdAtendimento = cdAtendimento;
		this.cdAutorizacaoSaida = cdAutorizacaoSaida;
		this.cdPaciente = cdPaciente;
	}

	@Column(name = "cd_observacao", nullable = false)
	public int getCdObservacao() {
		return this.cdObservacao;
	}

	public void setCdObservacao(int cdObservacao) {
		this.cdObservacao = cdObservacao;
	}

	@Column(name = "cd_atendimento", nullable = false)
	public int getCdAtendimento() {
		return this.cdAtendimento;
	}

	public void setCdAtendimento(int cdAtendimento) {
		this.cdAtendimento = cdAtendimento;
	}

	@Column(name = "cd_autorizacao_saida", nullable = false)
	public int getCdAutorizacaoSaida() {
		return this.cdAutorizacaoSaida;
	}

	public void setCdAutorizacaoSaida(int cdAutorizacaoSaida) {
		this.cdAutorizacaoSaida = cdAutorizacaoSaida;
	}

	@Column(name = "cd_paciente", nullable = false)
	public int getCdPaciente() {
		return this.cdPaciente;
	}

	public void setCdPaciente(int cdPaciente) {
		this.cdPaciente = cdPaciente;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ObservacoesId))
			return false;
		ObservacoesId castOther = (ObservacoesId) other;

		return (this.getCdObservacao() == castOther.getCdObservacao())
				&& (this.getCdAtendimento() == castOther.getCdAtendimento())
				&& (this.getCdAutorizacaoSaida() == castOther
						.getCdAutorizacaoSaida())
				&& (this.getCdPaciente() == castOther.getCdPaciente());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCdObservacao();
		result = 37 * result + this.getCdAtendimento();
		result = 37 * result + this.getCdAutorizacaoSaida();
		result = 37 * result + this.getCdPaciente();
		return result;
	}

}
