package entidades;

// Generated 01/09/2015 00:07:35 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;
import javax.persistence.Table;

/**
 * ResponsavelPacienteId generated by hbm2java
 */
@Entity
@Table(name = "responsavel_paciente", catalog = "rfid_maternidade")
public class ResponsavelPaciente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int responsavelCdResponsavel;
	private int pacienteCdPaciente;
	private int cdResponsavelPaciente;

	public ResponsavelPaciente(){
		
	}
	
	public ResponsavelPaciente(int pacienteCdPaciente, int cdResponsavelPaciente) {
		this.pacienteCdPaciente = pacienteCdPaciente;
		this.cdResponsavelPaciente = cdResponsavelPaciente;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "cd_responsavel_paciente", nullable = false)
	public int getCdResponsavelPaciente() {
		return cdResponsavelPaciente;
	}

	public void setCdResponsavelPaciente(int cdResponsavelPaciente) {
		this.cdResponsavelPaciente = cdResponsavelPaciente;
	}
	
	@Column(name = "responsavel_cd_responsavel", nullable = false)
	public int getResponsavelCdResponsavel() {
		return this.responsavelCdResponsavel;
	}

	public void setResponsavelCdResponsavel(int responsavelCdResponsavel) {
		this.responsavelCdResponsavel = responsavelCdResponsavel;
	}

	@Column(name = "paciente_cd_paciente", nullable = false)
	public int getPacienteCdPaciente() {
		return this.pacienteCdPaciente;
	}

	public void setPacienteCdPaciente(int pacienteCdPaciente) {
		this.pacienteCdPaciente = pacienteCdPaciente;
	}

}
