package entidades;

// Generated 01/09/2015 00:07:35 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ResponsavelPaciente generated by hbm2java
 */
@Entity
@Table(name = "responsavel_paciente", catalog = "rfid_maternidade")
public class ResponsavelPaciente implements java.io.Serializable {

	private ResponsavelPacienteId id;

	public ResponsavelPaciente() {
	}

	public ResponsavelPaciente(ResponsavelPacienteId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "responsavelCdResponsavel", column = @Column(name = "responsavel_cd_responsavel", nullable = false)),
			@AttributeOverride(name = "pacienteCdPaciente", column = @Column(name = "paciente_cd_paciente", nullable = false)) })
	public ResponsavelPacienteId getId() {
		return this.id;
	}

	public void setId(ResponsavelPacienteId id) {
		this.id = id;
	}

}
