package entidades;

// Generated 01/09/2015 00:07:35 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;

/**
 * ResponsavelPacienteId generated by hbm2java
 */
@Entity
public class ResponsavelPaciente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int responsavelCdResponsavel;
	private int pacienteCdPaciente;
	private int cdResponsavelPaciente;

	public ResponsavelPaciente() {
	}

	
	@Column(name = "responsavel_cd_responsavel", nullable = false)
	public int getResponsavelCdResponsavel() {
		return this.responsavelCdResponsavel;
	}

	public void setResponsavelCdResponsavel(int responsavelCdResponsavel) {
		this.responsavelCdResponsavel = responsavelCdResponsavel;
	}

	@Column(name = "paciente_cd_paciente", nullable = false)
	public int getPacienteCdPaciente() {
		return this.pacienteCdPaciente;
	}

	public void setPacienteCdPaciente(int pacienteCdPaciente) {
		this.pacienteCdPaciente = pacienteCdPaciente;
	}

	@Column(name = "cd_responsavel_paciente", nullable = false)
	public int getCdResponsavelPaciente() {
		return cdResponsavelPaciente;
	}

	public void setCdResponsavelPaciente(int cdResponsavelPaciente) {
		this.cdResponsavelPaciente = cdResponsavelPaciente;
	}


}
