package entidades;

// Generated 17/10/2015 19:11:37 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Responsavel generated by hbm2java
 */
@Entity
@Table(name = "responsavel", catalog = "rfid_maternidade")
public class Responsavel implements java.io.Serializable {

	private int cdResponsavel;
	private String nmResponsavel;
	private Set contatoResponsavels = new HashSet(0);
	private Set responsavelPacientes = new HashSet(0);

	public Responsavel() {
	}

	public Responsavel(int cdResponsavel) {
		this.cdResponsavel = cdResponsavel;
	}

	public Responsavel(int cdResponsavel, String nmResponsavel,
			Set contatoResponsavels, Set responsavelPacientes) {
		this.cdResponsavel = cdResponsavel;
		this.nmResponsavel = nmResponsavel;
		this.contatoResponsavels = contatoResponsavels;
		this.responsavelPacientes = responsavelPacientes;
	}

	@Id
	@Column(name = "cd_responsavel", unique = true, nullable = false)
	public int getCdResponsavel() {
		return this.cdResponsavel;
	}

	public void setCdResponsavel(int cdResponsavel) {
		this.cdResponsavel = cdResponsavel;
	}

	@Column(name = "nm_responsavel", length = 100)
	public String getNmResponsavel() {
		return this.nmResponsavel;
	}

	public void setNmResponsavel(String nmResponsavel) {
		this.nmResponsavel = nmResponsavel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "responsavel")
	public Set getContatoResponsavels() {
		return this.contatoResponsavels;
	}

	public void setContatoResponsavels(Set contatoResponsavels) {
		this.contatoResponsavels = contatoResponsavels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "responsavel")
	public Set getResponsavelPacientes() {
		return this.responsavelPacientes;
	}

	public void setResponsavelPacientes(Set responsavelPacientes) {
		this.responsavelPacientes = responsavelPacientes;
	}

}
