package entidades;

// Generated 01/09/2015 00:07:35 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SetorHasAtendimentoId generated by hbm2java
 */
@Embeddable
public class SetorHasAtendimentoId implements java.io.Serializable {

	private int setorCdSetor;
	private int atendimentoCdAtendimento;

	public SetorHasAtendimentoId() {
	}

	public SetorHasAtendimentoId(int setorCdSetor, int atendimentoCdAtendimento) {
		this.setorCdSetor = setorCdSetor;
		this.atendimentoCdAtendimento = atendimentoCdAtendimento;
	}

	@Column(name = "setor_cd_setor", nullable = false)
	public int getSetorCdSetor() {
		return this.setorCdSetor;
	}

	public void setSetorCdSetor(int setorCdSetor) {
		this.setorCdSetor = setorCdSetor;
	}

	@Column(name = "atendimento_cd_atendimento", nullable = false)
	public int getAtendimentoCdAtendimento() {
		return this.atendimentoCdAtendimento;
	}

	public void setAtendimentoCdAtendimento(int atendimentoCdAtendimento) {
		this.atendimentoCdAtendimento = atendimentoCdAtendimento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SetorHasAtendimentoId))
			return false;
		SetorHasAtendimentoId castOther = (SetorHasAtendimentoId) other;

		return (this.getSetorCdSetor() == castOther.getSetorCdSetor())
				&& (this.getAtendimentoCdAtendimento() == castOther
						.getAtendimentoCdAtendimento());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSetorCdSetor();
		result = 37 * result + this.getAtendimentoCdAtendimento();
		return result;
	}

}
