package entidades;

// Generated 01/09/2015 00:07:35 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Setor generated by hbm2java
 */
@Entity
@Table(name = "setor", catalog = "rfid_maternidade")
public class Setor implements java.io.Serializable {

	private int cdSetor;
	private String nmSetor;
	private String snAtivo;

	public Setor() {
	}

	public Setor(int cdSetor) {
		this.cdSetor = cdSetor;
	}

	public Setor(int cdSetor, String nmSetor, String snAtivo) {
		this.cdSetor = cdSetor;
		this.nmSetor = nmSetor;
		this.snAtivo = snAtivo;
	}

	@Id
	@Column(name = "cd_setor", unique = true, nullable = false)
	public int getCdSetor() {
		return this.cdSetor;
	}

	public void setCdSetor(int cdSetor) {
		this.cdSetor = cdSetor;
	}

	@Column(name = "nm_setor", length = 100)
	public String getNmSetor() {
		return this.nmSetor;
	}

	public void setNmSetor(String nmSetor) {
		this.nmSetor = nmSetor;
	}

	@Column(name = "sn_ativo", length = 1)
	public String getSnAtivo() {
		return this.snAtivo;
	}

	public void setSnAtivo(String snAtivo) {
		this.snAtivo = snAtivo;
	}

}
