package entidades;

// Generated 17/10/2015 19:11:37 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Setor generated by hbm2java
 */
@Entity
@Table(name = "setor", catalog = "rfid_maternidade")
public class Setor implements java.io.Serializable {

	private int cdSetor;
	private String nmSetor;
	private String snAtivo;
	private Set setorHasAtendimentos = new HashSet(0);
	private Set antenases = new HashSet(0);

	public Setor(int cdSetor, String nmSetor, String snAtivo) {
		this.cdSetor = cdSetor;
		this.nmSetor = nmSetor;
		this.snAtivo = snAtivo;
	}

	public Setor(int cdSetor) {
		this.cdSetor = cdSetor;
	}

	public Setor(int cdSetor, String nmSetor, String snAtivo,
			Set setorHasAtendimentos, Set antenases) {
		this.cdSetor = cdSetor;
		this.nmSetor = nmSetor;
		this.snAtivo = snAtivo;
		this.setorHasAtendimentos = setorHasAtendimentos;
		this.antenases = antenases;
	}

	@Id
	@Column(name = "cd_setor", unique = true, nullable = false)
	public int getCdSetor() {
		return this.cdSetor;
	}

	public void setCdSetor(int cdSetor) {
		this.cdSetor = cdSetor;
	}

	@Column(name = "nm_setor", length = 100)
	public String getNmSetor() {
		return this.nmSetor;
	}

	public void setNmSetor(String nmSetor) {
		this.nmSetor = nmSetor;
	}

	@Column(name = "sn_ativo", length = 1)
	public String getSnAtivo() {
		return this.snAtivo;
	}

	public void setSnAtivo(String snAtivo) {
		this.snAtivo = snAtivo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setor")
	public Set getSetorHasAtendimentos() {
		return this.setorHasAtendimentos;
	}

	public void setSetorHasAtendimentos(Set setorHasAtendimentos) {
		this.setorHasAtendimentos = setorHasAtendimentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setor")
	public Set getAntenases() {
		return this.antenases;
	}

	public void setAntenases(Set antenases) {
		this.antenases = antenases;
	}

}
