package entidades;

// Generated 01/09/2015 00:07:35 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SetorHasAtendimento generated by hbm2java
 */
@Entity
@Table(name = "setor_has_atendimento", catalog = "rfid_maternidade")
public class SetorHasAtendimento implements java.io.Serializable {

	private SetorHasAtendimentoId id;

	public SetorHasAtendimento() {
	}

	public SetorHasAtendimento(SetorHasAtendimentoId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "setorCdSetor", column = @Column(name = "setor_cd_setor", nullable = false)),
			@AttributeOverride(name = "atendimentoCdAtendimento", column = @Column(name = "atendimento_cd_atendimento", nullable = false)) })
	public SetorHasAtendimentoId getId() {
		return this.id;
	}

	public void setId(SetorHasAtendimentoId id) {
		this.id = id;
	}

}
