package entidades;

// Generated 17/10/2015 19:11:37 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TagsAtendimento generated by hbm2java
 */
@Entity
@Table(name = "tags_atendimento", catalog = "rfid_maternidade")
public class TagsAtendimento implements java.io.Serializable {

	private TagsAtendimentoId id;
	private Atendimento atendimento;
	private Tags tags;
	private String cdUsuario;
	private String snAtivo;
	private Date dtInativacao;

	public TagsAtendimento() {
	}

	public TagsAtendimento(TagsAtendimentoId id, Atendimento atendimento,
			Tags tags, String snAtivo) {
		this.id = id;
		this.atendimento = atendimento;
		this.tags = tags;
		this.snAtivo = snAtivo;
	}

	public TagsAtendimento(TagsAtendimentoId id, Atendimento atendimento,
			Tags tags, String cdUsuario, String snAtivo, Date dtInativacao) {
		this.id = id;
		this.atendimento = atendimento;
		this.tags = tags;
		this.cdUsuario = cdUsuario;
		this.snAtivo = snAtivo;
		this.dtInativacao = dtInativacao;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdTagAtendimento", column = @Column(name = "cd_tag_atendimento", nullable = false)),
			@AttributeOverride(name = "atendimentoCdAtendimento", column = @Column(name = "atendimento_cd_atendimento", nullable = false)),
			@AttributeOverride(name = "tagsCdTag", column = @Column(name = "tags_cd_tag", nullable = false)) })
	public TagsAtendimentoId getId() {
		return this.id;
	}

	public void setId(TagsAtendimentoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "atendimento_cd_atendimento", nullable = false, insertable = false, updatable = false)
	public Atendimento getAtendimento() {
		return this.atendimento;
	}

	public void setAtendimento(Atendimento atendimento) {
		this.atendimento = atendimento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tags_cd_tag", nullable = false, insertable = false, updatable = false)
	public Tags getTags() {
		return this.tags;
	}

	public void setTags(Tags tags) {
		this.tags = tags;
	}

	@Column(name = "cd_usuario", length = 20)
	public String getCdUsuario() {
		return this.cdUsuario;
	}

	public void setCdUsuario(String cdUsuario) {
		this.cdUsuario = cdUsuario;
	}

	@Column(name = "sn_ativo", nullable = false, length = 1)
	public String getSnAtivo() {
		return this.snAtivo;
	}

	public void setSnAtivo(String snAtivo) {
		this.snAtivo = snAtivo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_inativacao", length = 19)
	public Date getDtInativacao() {
		return this.dtInativacao;
	}

	public void setDtInativacao(Date dtInativacao) {
		this.dtInativacao = dtInativacao;
	}

}
