package entidades;

// Generated 17/10/2015 19:11:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TagsAtendimentoId generated by hbm2java
 */
@Embeddable
public class TagsAtendimentoId implements java.io.Serializable {

	private int cdTagAtendimento;
	private int atendimentoCdAtendimento;
	private int tagsCdTag;

	public TagsAtendimentoId() {
	}

	public TagsAtendimentoId(int cdTagAtendimento,
			int atendimentoCdAtendimento, int tagsCdTag) {
		this.cdTagAtendimento = cdTagAtendimento;
		this.atendimentoCdAtendimento = atendimentoCdAtendimento;
		this.tagsCdTag = tagsCdTag;
	}

	@Column(name = "cd_tag_atendimento", nullable = false)
	public int getCdTagAtendimento() {
		return this.cdTagAtendimento;
	}

	public void setCdTagAtendimento(int cdTagAtendimento) {
		this.cdTagAtendimento = cdTagAtendimento;
	}

	@Column(name = "atendimento_cd_atendimento", nullable = false)
	public int getAtendimentoCdAtendimento() {
		return this.atendimentoCdAtendimento;
	}

	public void setAtendimentoCdAtendimento(int atendimentoCdAtendimento) {
		this.atendimentoCdAtendimento = atendimentoCdAtendimento;
	}

	@Column(name = "tags_cd_tag", nullable = false)
	public int getTagsCdTag() {
		return this.tagsCdTag;
	}

	public void setTagsCdTag(int tagsCdTag) {
		this.tagsCdTag = tagsCdTag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TagsAtendimentoId))
			return false;
		TagsAtendimentoId castOther = (TagsAtendimentoId) other;

		return (this.getCdTagAtendimento() == castOther.getCdTagAtendimento())
				&& (this.getAtendimentoCdAtendimento() == castOther
						.getAtendimentoCdAtendimento())
				&& (this.getTagsCdTag() == castOther.getTagsCdTag());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCdTagAtendimento();
		result = 37 * result + this.getAtendimentoCdAtendimento();
		result = 37 * result + this.getTagsCdTag();
		return result;
	}

}
