package entidades;

// Generated 17/10/2015 19:11:37 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tags generated by hbm2java
 */
@Entity
@Table(name = "tags", catalog = "rfid_maternidade")
public class Tags implements java.io.Serializable {

	private Integer cdTag;
	private String cdTagFornecedor;
	private String snAtivo;
	private String snUso;
	private Set tagsAtendimentos = new HashSet(0);

	public Tags() {
	}

	public Tags(String cdTagFornecedor) {
		this.cdTagFornecedor = cdTagFornecedor;
	}

	public Tags(String cdTagFornecedor, String snAtivo, String snUso,
			Set tagsAtendimentos) {
		this.cdTagFornecedor = cdTagFornecedor;
		this.snAtivo = snAtivo;
		this.snUso = snUso;
		this.tagsAtendimentos = tagsAtendimentos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cd_tag", unique = true, nullable = false)
	public Integer getCdTag() {
		return this.cdTag;
	}

	public void setCdTag(Integer cdTag) {
		this.cdTag = cdTag;
	}

	@Column(name = "cd_tag_fornecedor", nullable = false, length = 100)
	public String getCdTagFornecedor() {
		return this.cdTagFornecedor;
	}

	public void setCdTagFornecedor(String cdTagFornecedor) {
		this.cdTagFornecedor = cdTagFornecedor;
	}

	@Column(name = "sn_ativo", length = 1)
	public String getSnAtivo() {
		return this.snAtivo;
	}

	public void setSnAtivo(String snAtivo) {
		this.snAtivo = snAtivo;
	}

	@Column(name = "sn_uso", length = 1)
	public String getSnUso() {
		return this.snUso;
	}

	public void setSnUso(String snUso) {
		this.snUso = snUso;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tags")
	public Set getTagsAtendimentos() {
		return this.tagsAtendimentos;
	}

	public void setTagsAtendimentos(Set tagsAtendimentos) {
		this.tagsAtendimentos = tagsAtendimentos;
	}

}
