package entidades;

// Generated 01/09/2015 00:07:35 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tags generated by hbm2java
 */
@Entity
@Table(name = "tags", catalog = "rfid_maternidade")
public class Tags implements java.io.Serializable {

	private int cdTag;
	private String cdTagFornecedor;
	private String snAtivo;
	private String snUso;

	public Tags() {
	}

	public Tags(int cdTag, String cdTagFornecedor) {
		this.cdTag = cdTag;
		this.cdTagFornecedor = cdTagFornecedor;
	}

	public Tags(int cdTag, String cdTagFornecedor, String snAtivo, String snUso) {
		this.cdTag = cdTag;
		this.cdTagFornecedor = cdTagFornecedor;
		this.snAtivo = snAtivo;
		this.snUso = snUso;
	}

	@Id
	@Column(name = "cd_tag", unique = true, nullable = false)
	public int getCdTag() {
		return this.cdTag;
	}

	public void setCdTag(int cdTag) {
		this.cdTag = cdTag;
	}

	@Column(name = "cd_tag_fornecedor", nullable = false, length = 100)
	public String getCdTagFornecedor() {
		return this.cdTagFornecedor;
	}

	public void setCdTagFornecedor(String cdTagFornecedor) {
		this.cdTagFornecedor = cdTagFornecedor;
	}

	@Column(name = "sn_ativo", length = 1)
	public String getSnAtivo() {
		return this.snAtivo;
	}

	public void setSnAtivo(String snAtivo) {
		this.snAtivo = snAtivo;
	}

	@Column(name = "sn_uso", length = 1)
	public String getSnUso() {
		return this.snUso;
	}

	public void setSnUso(String snUso) {
		this.snUso = snUso;
	}

}
