package entidades;

// Generated 01/09/2015 00:07:35 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TagsAtendimento generated by hbm2java
 */
@Entity
@Table(name = "tags_atendimento", catalog = "rfid_maternidade")
public class TagsAtendimento implements java.io.Serializable {

	private TagsAtendimentoId id;
	private String cdUsuario;
	private String snAtivo;
	private Date dtInativacao;

	public TagsAtendimento() {
	}

	public TagsAtendimento(TagsAtendimentoId id, String snAtivo) {
		this.id = id;
		this.snAtivo = snAtivo;
	}

	public TagsAtendimento(TagsAtendimentoId id, String cdUsuario,
			String snAtivo, Date dtInativacao) {
		this.id = id;
		this.cdUsuario = cdUsuario;
		this.snAtivo = snAtivo;
		this.dtInativacao = dtInativacao;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdTagAtendimento", column = @Column(name = "cd_tag_atendimento", nullable = false)),
			@AttributeOverride(name = "atendimentoCdAtendimento", column = @Column(name = "atendimento_cd_atendimento", nullable = false)),
			@AttributeOverride(name = "tagsCdTag", column = @Column(name = "tags_cd_tag", nullable = false)) })
	public TagsAtendimentoId getId() {
		return this.id;
	}

	public void setId(TagsAtendimentoId id) {
		this.id = id;
	}

	@Column(name = "cd_usuario", length = 20)
	public String getCdUsuario() {
		return this.cdUsuario;
	}

	public void setCdUsuario(String cdUsuario) {
		this.cdUsuario = cdUsuario;
	}

	@Column(name = "sn_ativo", nullable = false, length = 1)
	public String getSnAtivo() {
		return this.snAtivo;
	}

	public void setSnAtivo(String snAtivo) {
		this.snAtivo = snAtivo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_inativacao", length = 19)
	public Date getDtInativacao() {
		return this.dtInativacao;
	}

	public void setDtInativacao(Date dtInativacao) {
		this.dtInativacao = dtInativacao;
	}

}
