package entidades;

// Generated 01/09/2015 00:07:35 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TagsAtendimentoId generated by hbm2java
 */
@Entity
@Table(name = "tags_atendimento", catalog = "rfid_maternidade")
public class TagsAtendimento implements java.io.Serializable {

	private int cdTagAtendimento;
	private String cd_usuario;
	private int atendimentoCdAtendimento;
	private String cdTagFornecedor;
	private String snAtivo;
	private Date dtVinculo;
	private Date dtInativacao;

	public TagsAtendimento() {
	}
	
	public TagsAtendimento(String cd_usuario,int cdAtendimento, String cd_tag, String snAtivo, Date dtVinculo) {
		this.cd_usuario = cd_usuario;
		this.atendimentoCdAtendimento = cdAtendimento;
		this.cdTagFornecedor = cd_tag;
		this.snAtivo = snAtivo;
		this.dtVinculo = dtVinculo;
	}


	@Id
	@Column(name = "cd_tag_atendimento", nullable = false)
	public int getCdTagAtendimento() {
		return this.cdTagAtendimento;
	}

	public void setCdTagAtendimento(int cdTagAtendimento) {
		this.cdTagAtendimento = cdTagAtendimento;
	}

	@Column(name = "atendimento_cd_atendimento", nullable = false)
	public int getAtendimentoCdAtendimento() {
		return this.atendimentoCdAtendimento;
	}

	public void setAtendimentoCdAtendimento(int atendimentoCdAtendimento) {
		this.atendimentoCdAtendimento = atendimentoCdAtendimento;
	}

	@Column(name = "cd_usuario", nullable = false)
	public String getCd_usuario() {
		return cd_usuario;
	}

	public void setCd_usuario(String cd_usuario) {
		this.cd_usuario = cd_usuario;
	}

	@Column(name = "cd_tag_fornecedor", nullable = false)
	public String getCdTagFornecedor() {
		return cdTagFornecedor;
	}

	public void setCdTagFornecedor(String cdTagFornecedor) {
		this.cdTagFornecedor = cdTagFornecedor;
	}

	@Column(name = "sn_ativo", nullable = false)
	public String getSnAtivo() {
		return snAtivo;
	}

	public void setSnAtivo(String snAtivo) {
		this.snAtivo = snAtivo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_vinculo", nullable = false)
	public Date getDtVinculo() {
		return dtVinculo;
	}

	public void setDtVinculo(Date dtVinculo) {
		this.dtVinculo = dtVinculo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_inativacao", nullable = true)
	public Date getDtInativacao() {
		return dtInativacao;
	}

	public void setDtInativacao(Date dtInativacao) {
		this.dtInativacao = dtInativacao;
	}

	

}
