package entidades;

// Generated 01/09/2015 00:07:35 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoAlerta generated by hbm2java
 */
@Entity
@Table(name = "tipo_alerta", catalog = "rfid_maternidade")
public class TipoAlerta implements java.io.Serializable {

	private int cdTipoAlerta;
	private String dsTipoAlerta;

	public TipoAlerta() {
	}

	public TipoAlerta(int cdTipoAlerta, String dsTipoAlerta) {
		this.cdTipoAlerta = cdTipoAlerta;
		this.dsTipoAlerta = dsTipoAlerta;
	}

	@Id
	@Column(name = "cd_tipo_alerta", unique = true, nullable = false)
	public int getCdTipoAlerta() {
		return this.cdTipoAlerta;
	}

	public void setCdTipoAlerta(int cdTipoAlerta) {
		this.cdTipoAlerta = cdTipoAlerta;
	}

	@Column(name = "ds_tipo_alerta", nullable = false, length = 100)
	public String getDsTipoAlerta() {
		return this.dsTipoAlerta;
	}

	public void setDsTipoAlerta(String dsTipoAlerta) {
		this.dsTipoAlerta = dsTipoAlerta;
	}

}
