package entidades;

// Generated 17/10/2015 19:11:37 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoContato generated by hbm2java
 */
@Entity
@Table(name = "tipo_contato", catalog = "rfid_maternidade")
public class TipoContato implements java.io.Serializable {

	private int cdTipoContato;
	private String dsTipoContato;
	private Set contatoResponsavels = new HashSet(0);

	public TipoContato() {
	}

	public TipoContato(int cdTipoContato) {
		this.cdTipoContato = cdTipoContato;
	}

	public TipoContato(int cdTipoContato, String dsTipoContato,
			Set contatoResponsavels) {
		this.cdTipoContato = cdTipoContato;
		this.dsTipoContato = dsTipoContato;
		this.contatoResponsavels = contatoResponsavels;
	}

	@Id
	@Column(name = "cd_tipo_contato", unique = true, nullable = false)
	public int getCdTipoContato() {
		return this.cdTipoContato;
	}

	public void setCdTipoContato(int cdTipoContato) {
		this.cdTipoContato = cdTipoContato;
	}

	@Column(name = "ds_tipo_contato", length = 50)
	public String getDsTipoContato() {
		return this.dsTipoContato;
	}

	public void setDsTipoContato(String dsTipoContato) {
		this.dsTipoContato = dsTipoContato;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoContato")
	public Set getContatoResponsavels() {
		return this.contatoResponsavels;
	}

	public void setContatoResponsavels(Set contatoResponsavels) {
		this.contatoResponsavels = contatoResponsavels;
	}

}
