package entidades;

// Generated 17/10/2015 19:11:37 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoAlerta generated by hbm2java
 */
@Entity
@Table(name = "tipo_alerta", catalog = "rfid_maternidade")
public class TipoAlerta implements java.io.Serializable {

	private int cdTipoAlerta;
	private String dsTipoAlerta;
	private Set alertases = new HashSet(0);

	public TipoAlerta() {
	}

	public TipoAlerta(int cdTipoAlerta, String dsTipoAlerta) {
		this.cdTipoAlerta = cdTipoAlerta;
		this.dsTipoAlerta = dsTipoAlerta;
	}

	public TipoAlerta(int cdTipoAlerta, String dsTipoAlerta, Set alertases) {
		this.cdTipoAlerta = cdTipoAlerta;
		this.dsTipoAlerta = dsTipoAlerta;
		this.alertases = alertases;
	}

	@Id
	@Column(name = "cd_tipo_alerta", unique = true, nullable = false)
	public int getCdTipoAlerta() {
		return this.cdTipoAlerta;
	}

	public void setCdTipoAlerta(int cdTipoAlerta) {
		this.cdTipoAlerta = cdTipoAlerta;
	}

	@Column(name = "ds_tipo_alerta", nullable = false, length = 100)
	public String getDsTipoAlerta() {
		return this.dsTipoAlerta;
	}

	public void setDsTipoAlerta(String dsTipoAlerta) {
		this.dsTipoAlerta = dsTipoAlerta;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoAlerta")
	public Set getAlertases() {
		return this.alertases;
	}

	public void setAlertases(Set alertases) {
		this.alertases = alertases;
	}

}
