package entidades;


// Generated 22/10/2015 13:51:20 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UltimasMovimentacoesId generated by hbm2java
 */
@Embeddable
public class UltimasMovimentacoesId implements java.io.Serializable {

	private int cdTagAtendimento;
	private int antenasCdAntena;
	private Integer cdMovimentacao;
	private Date dtMovimentacao;

	public UltimasMovimentacoesId() {
	}

	public UltimasMovimentacoesId(int cdTagAtendimento, int antenasCdAntena) {
		this.cdTagAtendimento = cdTagAtendimento;
		this.antenasCdAntena = antenasCdAntena;
	}

	public UltimasMovimentacoesId(int cdTagAtendimento, int antenasCdAntena,
			Integer cdMovimentacao, Date dtMovimentacao) {
		this.cdTagAtendimento = cdTagAtendimento;
		this.antenasCdAntena = antenasCdAntena;
		this.cdMovimentacao = cdMovimentacao;
		this.dtMovimentacao = dtMovimentacao;
	}

	@Column(name = "cd_tag_atendimento", nullable = false)
	public int getCdTagAtendimento() {
		return this.cdTagAtendimento;
	}

	public void setCdTagAtendimento(int cdTagAtendimento) {
		this.cdTagAtendimento = cdTagAtendimento;
	}

	@Column(name = "antenas_cd_antena", nullable = false)
	public int getAntenasCdAntena() {
		return this.antenasCdAntena;
	}

	public void setAntenasCdAntena(int antenasCdAntena) {
		this.antenasCdAntena = antenasCdAntena;
	}

	@Column(name = "CD_MOVIMENTACAO")
	public Integer getCdMovimentacao() {
		return this.cdMovimentacao;
	}

	public void setCdMovimentacao(Integer cdMovimentacao) {
		this.cdMovimentacao = cdMovimentacao;
	}

	@Column(name = "DT_MOVIMENTACAO", length = 19)
	public Date getDtMovimentacao() {
		return this.dtMovimentacao;
	}

	public void setDtMovimentacao(Date dtMovimentacao) {
		this.dtMovimentacao = dtMovimentacao;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UltimasMovimentacoesId))
			return false;
		UltimasMovimentacoesId castOther = (UltimasMovimentacoesId) other;

		return (this.getCdTagAtendimento() == castOther.getCdTagAtendimento())
				&& (this.getAntenasCdAntena() == castOther.getAntenasCdAntena())
				&& ((this.getCdMovimentacao() == castOther.getCdMovimentacao()) || (this
						.getCdMovimentacao() != null
						&& castOther.getCdMovimentacao() != null && this
						.getCdMovimentacao().equals(
								castOther.getCdMovimentacao())))
				&& ((this.getDtMovimentacao() == castOther.getDtMovimentacao()) || (this
						.getDtMovimentacao() != null
						&& castOther.getDtMovimentacao() != null && this
						.getDtMovimentacao().equals(
								castOther.getDtMovimentacao())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCdTagAtendimento();
		result = 37 * result + this.getAntenasCdAntena();
		result = 37
				* result
				+ (getCdMovimentacao() == null ? 0 : this.getCdMovimentacao()
						.hashCode());
		result = 37
				* result
				+ (getDtMovimentacao() == null ? 0 : this.getDtMovimentacao()
						.hashCode());
		return result;
	}

}
