package entidades;

// Generated 01/09/2015 00:07:35 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Setor generated by hbm2java
 */
@Entity
@Table(name = "ultimas_movimentacoes_diferenca", catalog = "rfid_maternidade")
public class UltimasMovimentacoesDiferenca implements java.io.Serializable {

	private int cdAtendimento;
	private int cdPaciente;
	private String nmPaciente;
	private String cdTagFornecedor;
	private Date dtMovimentacao;
	private int cdAntena;
	private String dsAntena;
	private int cdSetor;
	private String nmSetor;
	private int cdMovimentacao;
	private int diferenca;

	
	
	

	@Column(name = "cd_setor")
	public int getCdSetor() {
		return cdSetor;
	}

	public void setCdSetor(int cdSetor) {
		this.cdSetor = cdSetor;
	}

	@Column(name = "nm_setor")
	public String getNmSetor() {
		return nmSetor;
	}

	public void setNmSetor(String nmSetor) {
		this.nmSetor = nmSetor;
	}

	@Column(name = "diferenca")
	public int getDiferenca() {
		return diferenca;
	}

	public void setDiferenca(int diferenca) {
		this.diferenca = diferenca;
	}

	@Id
	@Column(name = "cd_atendimento")
	public int getCdAtendimento() {
		return cdAtendimento;
	}

	public void setCdAtendimento(int cdAtendimento) {
		this.cdAtendimento = cdAtendimento;
	}

	@Column(name = "cd_paciente")
	public int getCdPaciente() {
		return cdPaciente;
	}

	public void setCdPaciente(int cdPaciente) {
		this.cdPaciente = cdPaciente;
	}

	@Column(name = "nm_paciente")
	public String getNmPaciente() {
		return nmPaciente;
	}

	public void setNmPaciente(String nmPaciente) {
		this.nmPaciente = nmPaciente;
	}

	@Column(name = "cd_tag_fornecedor")
	public String getCdTagFornecedor() {
		return cdTagFornecedor;
	}

	public void setCdTagFornecedor(String cdTagFornecedor) {
		this.cdTagFornecedor = cdTagFornecedor;
	}
	@Temporal(value = TemporalType.TIMESTAMP)
	@Column(name = "dt_movimentacao")
	public Date getDtMovimentacao() {
		return dtMovimentacao;
	}

	public void setDtMovimentacao(Date dtMovimentacao) {
		this.dtMovimentacao = dtMovimentacao;
	}

	@Column(name = "cd_antena")
	public int getCdAntena() {
		return cdAntena;
	}

	public void setCdAntena(int cdAntena) {
		this.cdAntena = cdAntena;
	}

	@Column(name = "ds_antena")
	public String getDsAntena() {
		return dsAntena;
	}

	public void setDsAntena(String dsAntena) {
		this.dsAntena = dsAntena;
	}

	@Column(name = "cd_movimentacao")
	public int getCdMovimentacao() {
		return cdMovimentacao;
	}

	public void setCdMovimentacao(int cdMovimentacao) {
		this.cdMovimentacao = cdMovimentacao;
	}

	public UltimasMovimentacoesDiferenca() {
	}

	public UltimasMovimentacoesDiferenca(int cdSetor) {
		this.cdSetor = cdSetor;
	}



}
