package entidades;



// Generated 22/10/2015 13:51:20 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UltimasMovimentacoes generated by hbm2java
 */
@Entity
@Table(name = "ultimas_movimentacoes", catalog = "rfid_maternidade")
public class UltimasMovimentacoes implements java.io.Serializable {

	private UltimasMovimentacoesId id;

	public UltimasMovimentacoes() {
	}

	public UltimasMovimentacoes(UltimasMovimentacoesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdTagAtendimento", column = @Column(name = "cd_tag_atendimento", nullable = false)),
			@AttributeOverride(name = "antenasCdAntena", column = @Column(name = "antenas_cd_antena", nullable = false)),
			@AttributeOverride(name = "cdMovimentacao", column = @Column(name = "CD_MOVIMENTACAO")),
			@AttributeOverride(name = "dtMovimentacao", column = @Column(name = "DT_MOVIMENTACAO", length = 19)) })
	public UltimasMovimentacoesId getId() {
		return this.id;
	}

	public void setId(UltimasMovimentacoesId id) {
		this.id = id;
	}

}
