package entidades;

// Generated 01/09/2015 00:07:35 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UsuarioHasModulo generated by hbm2java
 */
@Entity
@Table(name = "usuario_has_modulo", catalog = "rfid_maternidade")
public class UsuarioHasModulo implements java.io.Serializable {

	private UsuarioHasModuloId id;

	public UsuarioHasModulo() {
	}

	public UsuarioHasModulo(UsuarioHasModuloId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "usuarioCdUsuario", column = @Column(name = "usuario_cd_usuario", nullable = false, length = 20)),
			@AttributeOverride(name = "moduloCdModulo", column = @Column(name = "modulo_cd_modulo", nullable = false)) })
	public UsuarioHasModuloId getId() {
		return this.id;
	}

	public void setId(UsuarioHasModuloId id) {
		this.id = id;
	}

}
