package entidades;

// Generated 01/09/2015 00:07:35 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuarioHasModuloId generated by hbm2java
 */
@Embeddable
public class UsuarioHasModuloId implements java.io.Serializable {

	private String usuarioCdUsuario;
	private int moduloCdModulo;

	public UsuarioHasModuloId() {
	}

	public UsuarioHasModuloId(String usuarioCdUsuario, int moduloCdModulo) {
		this.usuarioCdUsuario = usuarioCdUsuario;
		this.moduloCdModulo = moduloCdModulo;
	}

	@Column(name = "usuario_cd_usuario", nullable = false, length = 20)
	public String getUsuarioCdUsuario() {
		return this.usuarioCdUsuario;
	}

	public void setUsuarioCdUsuario(String usuarioCdUsuario) {
		this.usuarioCdUsuario = usuarioCdUsuario;
	}

	@Column(name = "modulo_cd_modulo", nullable = false)
	public int getModuloCdModulo() {
		return this.moduloCdModulo;
	}

	public void setModuloCdModulo(int moduloCdModulo) {
		this.moduloCdModulo = moduloCdModulo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioHasModuloId))
			return false;
		UsuarioHasModuloId castOther = (UsuarioHasModuloId) other;

		return ((this.getUsuarioCdUsuario() == castOther.getUsuarioCdUsuario()) || (this
				.getUsuarioCdUsuario() != null
				&& castOther.getUsuarioCdUsuario() != null && this
				.getUsuarioCdUsuario().equals(castOther.getUsuarioCdUsuario())))
				&& (this.getModuloCdModulo() == castOther.getModuloCdModulo());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getUsuarioCdUsuario() == null ? 0 : this
						.getUsuarioCdUsuario().hashCode());
		result = 37 * result + this.getModuloCdModulo();
		return result;
	}

}
