package entidades;

// Generated 01/09/2015 00:07:35 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "rfid_maternidade")
public class Usuario implements java.io.Serializable {

	private String cdUsuario;
	private String nmUsuario;
	private String cpf;
	private Date dtNascimento;
	private Date dtCadastro;
	private String senha;

	public Usuario() {
	}

	public Usuario(String cdUsuario, String senha) {
		this.cdUsuario = cdUsuario;
		this.senha = senha;
	}

	public Usuario(String cdUsuario, String nmUsuario, String cpf,
			Date dtNascimento, Date dtCadastro, String senha) {
		this.cdUsuario = cdUsuario;
		this.nmUsuario = nmUsuario;
		this.cpf = cpf;
		this.dtNascimento = dtNascimento;
		this.dtCadastro = dtCadastro;
		this.senha = senha;
	}

	@Id
	@Column(name = "cd_usuario", unique = true, nullable = false, length = 20)
	public String getCdUsuario() {
		return this.cdUsuario;
	}

	public void setCdUsuario(String cdUsuario) {
		this.cdUsuario = cdUsuario;
	}

	@Column(name = "nm_usuario", length = 100)
	public String getNmUsuario() {
		return this.nmUsuario;
	}

	public void setNmUsuario(String nmUsuario) {
		this.nmUsuario = nmUsuario;
	}

	@Column(name = "cpf", length = 11)
	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_nascimento", length = 10)
	public Date getDtNascimento() {
		return this.dtNascimento;
	}

	public void setDtNascimento(Date dtNascimento) {
		this.dtNascimento = dtNascimento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_cadastro", length = 10)
	public Date getDtCadastro() {
		return this.dtCadastro;
	}

	public void setDtCadastro(Date dtCadastro) {
		this.dtCadastro = dtCadastro;
	}

	@Column(name = "senha", nullable = false, length = 32)
	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

}
